/* 
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: v2
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Domain.Client.SwaggerDateConverter;

namespace Domain.Model
{
    /// <summary>
    /// APMAPIModelsSuburbV2SeriesModel
    /// </summary>
    [DataContract]
        public partial class APMAPIModelsSuburbV2SeriesModel :  IEquatable<APMAPIModelsSuburbV2SeriesModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="APMAPIModelsSuburbV2SeriesModel" /> class.
        /// </summary>
        /// <param name="seriesInfo">seriesInfo.</param>
        public APMAPIModelsSuburbV2SeriesModel(List<APMAPIModelsSuburbV2SeriesInfoModel> seriesInfo = default(List<APMAPIModelsSuburbV2SeriesInfoModel>))
        {
            this.SeriesInfo = seriesInfo;
        }
        
        /// <summary>
        /// Gets or Sets SeriesInfo
        /// </summary>
        [DataMember(Name="seriesInfo", EmitDefaultValue=false)]
        public List<APMAPIModelsSuburbV2SeriesInfoModel> SeriesInfo { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class APMAPIModelsSuburbV2SeriesModel {\n");
            sb.Append("  SeriesInfo: ").Append(SeriesInfo).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as APMAPIModelsSuburbV2SeriesModel);
        }

        /// <summary>
        /// Returns true if APMAPIModelsSuburbV2SeriesModel instances are equal
        /// </summary>
        /// <param name="input">Instance of APMAPIModelsSuburbV2SeriesModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(APMAPIModelsSuburbV2SeriesModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.SeriesInfo == input.SeriesInfo ||
                    this.SeriesInfo != null &&
                    input.SeriesInfo != null &&
                    this.SeriesInfo.SequenceEqual(input.SeriesInfo)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.SeriesInfo != null)
                    hashCode = hashCode * 59 + this.SeriesInfo.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
