/* 
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: v2
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Domain.Client.SwaggerDateConverter;

namespace Domain.Model
{
    /// <summary>
    /// Residential off market property
    /// </summary>
    [DataContract]
        public partial class ListingAdminV2ResidentialOffMarketProperty :  IEquatable<ListingAdminV2ResidentialOffMarketProperty>, IValidatableObject
    {
        /// <summary>
        /// Defines PropertyType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum PropertyTypeEnum
        {
            /// <summary>
            /// Enum AcreageSemiRural for value: acreageSemiRural
            /// </summary>
            [EnumMember(Value = "acreageSemiRural")]
            AcreageSemiRural = 1,
            /// <summary>
            /// Enum ApartmentUnitFlat for value: apartmentUnitFlat
            /// </summary>
            [EnumMember(Value = "apartmentUnitFlat")]
            ApartmentUnitFlat = 2,
            /// <summary>
            /// Enum Aquaculture for value: aquaculture
            /// </summary>
            [EnumMember(Value = "aquaculture")]
            Aquaculture = 3,
            /// <summary>
            /// Enum BlockOfUnits for value: blockOfUnits
            /// </summary>
            [EnumMember(Value = "blockOfUnits")]
            BlockOfUnits = 4,
            /// <summary>
            /// Enum CarSpace for value: carSpace
            /// </summary>
            [EnumMember(Value = "carSpace")]
            CarSpace = 5,
            /// <summary>
            /// Enum DairyFarming for value: dairyFarming
            /// </summary>
            [EnumMember(Value = "dairyFarming")]
            DairyFarming = 6,
            /// <summary>
            /// Enum DevelopmentSite for value: developmentSite
            /// </summary>
            [EnumMember(Value = "developmentSite")]
            DevelopmentSite = 7,
            /// <summary>
            /// Enum Duplex for value: duplex
            /// </summary>
            [EnumMember(Value = "duplex")]
            Duplex = 8,
            /// <summary>
            /// Enum Farm for value: farm
            /// </summary>
            [EnumMember(Value = "farm")]
            Farm = 9,
            /// <summary>
            /// Enum FishingForestry for value: fishingForestry
            /// </summary>
            [EnumMember(Value = "fishingForestry")]
            FishingForestry = 10,
            /// <summary>
            /// Enum NewHomeDesigns for value: newHomeDesigns
            /// </summary>
            [EnumMember(Value = "newHomeDesigns")]
            NewHomeDesigns = 11,
            /// <summary>
            /// Enum House for value: house
            /// </summary>
            [EnumMember(Value = "house")]
            House = 12,
            /// <summary>
            /// Enum NewHouseLand for value: newHouseLand
            /// </summary>
            [EnumMember(Value = "newHouseLand")]
            NewHouseLand = 13,
            /// <summary>
            /// Enum IrrigationServices for value: irrigationServices
            /// </summary>
            [EnumMember(Value = "irrigationServices")]
            IrrigationServices = 14,
            /// <summary>
            /// Enum NewLand for value: newLand
            /// </summary>
            [EnumMember(Value = "newLand")]
            NewLand = 15,
            /// <summary>
            /// Enum Livestock for value: livestock
            /// </summary>
            [EnumMember(Value = "livestock")]
            Livestock = 16,
            /// <summary>
            /// Enum NewApartments for value: newApartments
            /// </summary>
            [EnumMember(Value = "newApartments")]
            NewApartments = 17,
            /// <summary>
            /// Enum Penthouse for value: penthouse
            /// </summary>
            [EnumMember(Value = "penthouse")]
            Penthouse = 18,
            /// <summary>
            /// Enum Retirement for value: retirement
            /// </summary>
            [EnumMember(Value = "retirement")]
            Retirement = 19,
            /// <summary>
            /// Enum Rural for value: rural
            /// </summary>
            [EnumMember(Value = "rural")]
            Rural = 20,
            /// <summary>
            /// Enum SemiDetached for value: semiDetached
            /// </summary>
            [EnumMember(Value = "semiDetached")]
            SemiDetached = 21,
            /// <summary>
            /// Enum SpecialistFarm for value: specialistFarm
            /// </summary>
            [EnumMember(Value = "specialistFarm")]
            SpecialistFarm = 22,
            /// <summary>
            /// Enum Studio for value: studio
            /// </summary>
            [EnumMember(Value = "studio")]
            Studio = 23,
            /// <summary>
            /// Enum Terrace for value: terrace
            /// </summary>
            [EnumMember(Value = "terrace")]
            Terrace = 24,
            /// <summary>
            /// Enum Townhouse for value: townhouse
            /// </summary>
            [EnumMember(Value = "townhouse")]
            Townhouse = 25,
            /// <summary>
            /// Enum VacantLand for value: vacantLand
            /// </summary>
            [EnumMember(Value = "vacantLand")]
            VacantLand = 26,
            /// <summary>
            /// Enum Villa for value: villa
            /// </summary>
            [EnumMember(Value = "villa")]
            Villa = 27,
            /// <summary>
            /// Enum Cropping for value: cropping
            /// </summary>
            [EnumMember(Value = "cropping")]
            Cropping = 28,
            /// <summary>
            /// Enum Viticulture for value: viticulture
            /// </summary>
            [EnumMember(Value = "viticulture")]
            Viticulture = 29,
            /// <summary>
            /// Enum MixedFarming for value: mixedFarming
            /// </summary>
            [EnumMember(Value = "mixedFarming")]
            MixedFarming = 30,
            /// <summary>
            /// Enum Grazing for value: grazing
            /// </summary>
            [EnumMember(Value = "grazing")]
            Grazing = 31,
            /// <summary>
            /// Enum Horticulture for value: horticulture
            /// </summary>
            [EnumMember(Value = "horticulture")]
            Horticulture = 32,
            /// <summary>
            /// Enum Equine for value: equine
            /// </summary>
            [EnumMember(Value = "equine")]
            Equine = 33,
            /// <summary>
            /// Enum Farmlet for value: farmlet
            /// </summary>
            [EnumMember(Value = "farmlet")]
            Farmlet = 34,
            /// <summary>
            /// Enum Orchard for value: orchard
            /// </summary>
            [EnumMember(Value = "orchard")]
            Orchard = 35,
            /// <summary>
            /// Enum RuralLifestyle for value: ruralLifestyle
            /// </summary>
            [EnumMember(Value = "ruralLifestyle")]
            RuralLifestyle = 36        }
        /// <summary>
        /// Residential property types&lt;br /&gt;  &#x27;Retirement&#x27; requires at least one more property type to be specified with it (for example: \&quot;Retirement, ApartmentUnitFlat\&quot;) [&#x27;acreageSemiRural&#x27;, &#x27;apartmentUnitFlat&#x27;, &#x27;aquaculture&#x27;, &#x27;blockOfUnits&#x27;, &#x27;carSpace&#x27;, &#x27;dairyFarming&#x27;, &#x27;developmentSite&#x27;, &#x27;duplex&#x27;, &#x27;farm&#x27;, &#x27;fishingForestry&#x27;, &#x27;newHomeDesigns&#x27;, &#x27;house&#x27;, &#x27;newHouseLand&#x27;, &#x27;irrigationServices&#x27;, &#x27;newLand&#x27;, &#x27;livestock&#x27;, &#x27;newApartments&#x27;, &#x27;penthouse&#x27;, &#x27;retirement&#x27;, &#x27;rural&#x27;, &#x27;semiDetached&#x27;, &#x27;specialistFarm&#x27;, &#x27;studio&#x27;, &#x27;terrace&#x27;, &#x27;townhouse&#x27;, &#x27;vacantLand&#x27;, &#x27;villa&#x27;, &#x27;cropping&#x27;, &#x27;viticulture&#x27;, &#x27;mixedFarming&#x27;, &#x27;grazing&#x27;, &#x27;horticulture&#x27;, &#x27;equine&#x27;, &#x27;farmlet&#x27;, &#x27;orchard&#x27;, &#x27;ruralLifestyle&#x27;].
        /// </summary>
        /// <value>Residential property types&lt;br /&gt;  &#x27;Retirement&#x27; requires at least one more property type to be specified with it (for example: \&quot;Retirement, ApartmentUnitFlat\&quot;) [&#x27;acreageSemiRural&#x27;, &#x27;apartmentUnitFlat&#x27;, &#x27;aquaculture&#x27;, &#x27;blockOfUnits&#x27;, &#x27;carSpace&#x27;, &#x27;dairyFarming&#x27;, &#x27;developmentSite&#x27;, &#x27;duplex&#x27;, &#x27;farm&#x27;, &#x27;fishingForestry&#x27;, &#x27;newHomeDesigns&#x27;, &#x27;house&#x27;, &#x27;newHouseLand&#x27;, &#x27;irrigationServices&#x27;, &#x27;newLand&#x27;, &#x27;livestock&#x27;, &#x27;newApartments&#x27;, &#x27;penthouse&#x27;, &#x27;retirement&#x27;, &#x27;rural&#x27;, &#x27;semiDetached&#x27;, &#x27;specialistFarm&#x27;, &#x27;studio&#x27;, &#x27;terrace&#x27;, &#x27;townhouse&#x27;, &#x27;vacantLand&#x27;, &#x27;villa&#x27;, &#x27;cropping&#x27;, &#x27;viticulture&#x27;, &#x27;mixedFarming&#x27;, &#x27;grazing&#x27;, &#x27;horticulture&#x27;, &#x27;equine&#x27;, &#x27;farmlet&#x27;, &#x27;orchard&#x27;, &#x27;ruralLifestyle&#x27;].</value>
        [DataMember(Name="propertyType", EmitDefaultValue=false)]
        public List<PropertyTypeEnum> PropertyType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ListingAdminV2ResidentialOffMarketProperty" /> class.
        /// </summary>
        /// <param name="propertyType">Residential property types&lt;br /&gt;  &#x27;Retirement&#x27; requires at least one more property type to be specified with it (for example: \&quot;Retirement, ApartmentUnitFlat\&quot;) [&#x27;acreageSemiRural&#x27;, &#x27;apartmentUnitFlat&#x27;, &#x27;aquaculture&#x27;, &#x27;blockOfUnits&#x27;, &#x27;carSpace&#x27;, &#x27;dairyFarming&#x27;, &#x27;developmentSite&#x27;, &#x27;duplex&#x27;, &#x27;farm&#x27;, &#x27;fishingForestry&#x27;, &#x27;newHomeDesigns&#x27;, &#x27;house&#x27;, &#x27;newHouseLand&#x27;, &#x27;irrigationServices&#x27;, &#x27;newLand&#x27;, &#x27;livestock&#x27;, &#x27;newApartments&#x27;, &#x27;penthouse&#x27;, &#x27;retirement&#x27;, &#x27;rural&#x27;, &#x27;semiDetached&#x27;, &#x27;specialistFarm&#x27;, &#x27;studio&#x27;, &#x27;terrace&#x27;, &#x27;townhouse&#x27;, &#x27;vacantLand&#x27;, &#x27;villa&#x27;, &#x27;cropping&#x27;, &#x27;viticulture&#x27;, &#x27;mixedFarming&#x27;, &#x27;grazing&#x27;, &#x27;horticulture&#x27;, &#x27;equine&#x27;, &#x27;farmlet&#x27;, &#x27;orchard&#x27;, &#x27;ruralLifestyle&#x27;]. (required).</param>
        /// <param name="bedRooms">Number of bedrooms.</param>
        /// <param name="bathRooms">Number of bathrooms.</param>
        /// <param name="parkingInfo">parkingInfo.</param>
        /// <param name="images">List of image files, photos or floor plans related to the listing..</param>
        /// <param name="address">address (required).</param>
        /// <param name="area">area.</param>
        /// <param name="landArea">landArea.</param>
        public ListingAdminV2ResidentialOffMarketProperty(List<PropertyTypeEnum> propertyType = default(List<PropertyTypeEnum>), int? bedRooms = default(int?), int? bathRooms = default(int?), ListingAdminV2ParkingInfo parkingInfo = default(ListingAdminV2ParkingInfo), List<ListingAdminV2PropertyMedia> images = default(List<ListingAdminV2PropertyMedia>), ListingAdminV2Address address = default(ListingAdminV2Address), ListingAdminV2Area area = default(ListingAdminV2Area), ListingAdminV2LandArea landArea = default(ListingAdminV2LandArea))
        {
            // to ensure "propertyType" is required (not null)
            if (propertyType == null)
            {
                throw new InvalidDataException("propertyType is a required property for ListingAdminV2ResidentialOffMarketProperty and cannot be null");
            }
            else
            {
                this.PropertyType = propertyType;
            }
            // to ensure "address" is required (not null)
            if (address == null)
            {
                throw new InvalidDataException("address is a required property for ListingAdminV2ResidentialOffMarketProperty and cannot be null");
            }
            else
            {
                this.Address = address;
            }
            this.BedRooms = bedRooms;
            this.BathRooms = bathRooms;
            this.ParkingInfo = parkingInfo;
            this.Images = images;
            this.Area = area;
            this.LandArea = landArea;
        }
        

        /// <summary>
        /// Number of bedrooms
        /// </summary>
        /// <value>Number of bedrooms</value>
        [DataMember(Name="bedRooms", EmitDefaultValue=false)]
        public int? BedRooms { get; set; }

        /// <summary>
        /// Number of bathrooms
        /// </summary>
        /// <value>Number of bathrooms</value>
        [DataMember(Name="bathRooms", EmitDefaultValue=false)]
        public int? BathRooms { get; set; }

        /// <summary>
        /// Gets or Sets ParkingInfo
        /// </summary>
        [DataMember(Name="parkingInfo", EmitDefaultValue=false)]
        public ListingAdminV2ParkingInfo ParkingInfo { get; set; }

        /// <summary>
        /// List of image files, photos or floor plans related to the listing.
        /// </summary>
        /// <value>List of image files, photos or floor plans related to the listing.</value>
        [DataMember(Name="images", EmitDefaultValue=false)]
        public List<ListingAdminV2PropertyMedia> Images { get; set; }

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [DataMember(Name="address", EmitDefaultValue=false)]
        public ListingAdminV2Address Address { get; set; }

        /// <summary>
        /// Gets or Sets Area
        /// </summary>
        [DataMember(Name="area", EmitDefaultValue=false)]
        public ListingAdminV2Area Area { get; set; }

        /// <summary>
        /// Gets or Sets LandArea
        /// </summary>
        [DataMember(Name="landArea", EmitDefaultValue=false)]
        public ListingAdminV2LandArea LandArea { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ListingAdminV2ResidentialOffMarketProperty {\n");
            sb.Append("  PropertyType: ").Append(PropertyType).Append("\n");
            sb.Append("  BedRooms: ").Append(BedRooms).Append("\n");
            sb.Append("  BathRooms: ").Append(BathRooms).Append("\n");
            sb.Append("  ParkingInfo: ").Append(ParkingInfo).Append("\n");
            sb.Append("  Images: ").Append(Images).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  Area: ").Append(Area).Append("\n");
            sb.Append("  LandArea: ").Append(LandArea).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ListingAdminV2ResidentialOffMarketProperty);
        }

        /// <summary>
        /// Returns true if ListingAdminV2ResidentialOffMarketProperty instances are equal
        /// </summary>
        /// <param name="input">Instance of ListingAdminV2ResidentialOffMarketProperty to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ListingAdminV2ResidentialOffMarketProperty input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.PropertyType == input.PropertyType ||
                    this.PropertyType != null &&
                    input.PropertyType != null &&
                    this.PropertyType.SequenceEqual(input.PropertyType)
                ) && 
                (
                    this.BedRooms == input.BedRooms ||
                    (this.BedRooms != null &&
                    this.BedRooms.Equals(input.BedRooms))
                ) && 
                (
                    this.BathRooms == input.BathRooms ||
                    (this.BathRooms != null &&
                    this.BathRooms.Equals(input.BathRooms))
                ) && 
                (
                    this.ParkingInfo == input.ParkingInfo ||
                    (this.ParkingInfo != null &&
                    this.ParkingInfo.Equals(input.ParkingInfo))
                ) && 
                (
                    this.Images == input.Images ||
                    this.Images != null &&
                    input.Images != null &&
                    this.Images.SequenceEqual(input.Images)
                ) && 
                (
                    this.Address == input.Address ||
                    (this.Address != null &&
                    this.Address.Equals(input.Address))
                ) && 
                (
                    this.Area == input.Area ||
                    (this.Area != null &&
                    this.Area.Equals(input.Area))
                ) && 
                (
                    this.LandArea == input.LandArea ||
                    (this.LandArea != null &&
                    this.LandArea.Equals(input.LandArea))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.PropertyType != null)
                    hashCode = hashCode * 59 + this.PropertyType.GetHashCode();
                if (this.BedRooms != null)
                    hashCode = hashCode * 59 + this.BedRooms.GetHashCode();
                if (this.BathRooms != null)
                    hashCode = hashCode * 59 + this.BathRooms.GetHashCode();
                if (this.ParkingInfo != null)
                    hashCode = hashCode * 59 + this.ParkingInfo.GetHashCode();
                if (this.Images != null)
                    hashCode = hashCode * 59 + this.Images.GetHashCode();
                if (this.Address != null)
                    hashCode = hashCode * 59 + this.Address.GetHashCode();
                if (this.Area != null)
                    hashCode = hashCode * 59 + this.Area.GetHashCode();
                if (this.LandArea != null)
                    hashCode = hashCode * 59 + this.LandArea.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
