/* 
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: v2
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Domain.Client.SwaggerDateConverter;

namespace Domain.Model
{
    /// <summary>
    /// Inspection times
    /// </summary>
    [DataContract]
        public partial class ListingAdminV2Inspection :  IEquatable<ListingAdminV2Inspection>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ListingAdminV2Inspection" /> class.
        /// </summary>
        /// <param name="from">Format: yyyy-mm-dd HH:mm:ss eg: 2015-10-20 13:30:00 (required).</param>
        /// <param name="to">Format: yyyy-mm-dd HH:mm:ss, eg: 2015-10-20 14:30:00 (required).</param>
        /// <param name="repeat">Specifies if the inspection is recurring weekly.</param>
        public ListingAdminV2Inspection(DateTime? from = default(DateTime?), DateTime? to = default(DateTime?), bool? repeat = default(bool?))
        {
            // to ensure "from" is required (not null)
            if (from == null)
            {
                throw new InvalidDataException("from is a required property for ListingAdminV2Inspection and cannot be null");
            }
            else
            {
                this.From = from;
            }
            // to ensure "to" is required (not null)
            if (to == null)
            {
                throw new InvalidDataException("to is a required property for ListingAdminV2Inspection and cannot be null");
            }
            else
            {
                this.To = to;
            }
            this.Repeat = repeat;
        }
        
        /// <summary>
        /// Format: yyyy-mm-dd HH:mm:ss eg: 2015-10-20 13:30:00
        /// </summary>
        /// <value>Format: yyyy-mm-dd HH:mm:ss eg: 2015-10-20 13:30:00</value>
        [DataMember(Name="from", EmitDefaultValue=false)]
        public DateTime? From { get; set; }

        /// <summary>
        /// Format: yyyy-mm-dd HH:mm:ss, eg: 2015-10-20 14:30:00
        /// </summary>
        /// <value>Format: yyyy-mm-dd HH:mm:ss, eg: 2015-10-20 14:30:00</value>
        [DataMember(Name="to", EmitDefaultValue=false)]
        public DateTime? To { get; set; }

        /// <summary>
        /// Specifies if the inspection is recurring weekly
        /// </summary>
        /// <value>Specifies if the inspection is recurring weekly</value>
        [DataMember(Name="repeat", EmitDefaultValue=false)]
        public bool? Repeat { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ListingAdminV2Inspection {\n");
            sb.Append("  From: ").Append(From).Append("\n");
            sb.Append("  To: ").Append(To).Append("\n");
            sb.Append("  Repeat: ").Append(Repeat).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ListingAdminV2Inspection);
        }

        /// <summary>
        /// Returns true if ListingAdminV2Inspection instances are equal
        /// </summary>
        /// <param name="input">Instance of ListingAdminV2Inspection to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ListingAdminV2Inspection input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.From == input.From ||
                    (this.From != null &&
                    this.From.Equals(input.From))
                ) && 
                (
                    this.To == input.To ||
                    (this.To != null &&
                    this.To.Equals(input.To))
                ) && 
                (
                    this.Repeat == input.Repeat ||
                    (this.Repeat != null &&
                    this.Repeat.Equals(input.Repeat))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.From != null)
                    hashCode = hashCode * 59 + this.From.GetHashCode();
                if (this.To != null)
                    hashCode = hashCode * 59 + this.To.GetHashCode();
                if (this.Repeat != null)
                    hashCode = hashCode * 59 + this.Repeat.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
