/* 
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: v2
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Domain.Client.SwaggerDateConverter;

namespace Domain.Model
{
    /// <summary>
    /// PDF file related to the listing
    /// </summary>
    [DataContract]
        public partial class ListingAdminV2PropertyPdf :  IEquatable<ListingAdminV2PropertyPdf>, IValidatableObject
    {
        /// <summary>
        /// Type of the PDF
        /// </summary>
        /// <value>Type of the PDF</value>
        [JsonConverter(typeof(StringEnumConverter))]
                public enum TypeEnum
        {
            /// <summary>
            /// Enum CommercialPdf for value: commercialPdf
            /// </summary>
            [EnumMember(Value = "commercialPdf")]
            CommercialPdf = 1,
            /// <summary>
            /// Enum NewDevBrochurePdf for value: newDevBrochurePdf
            /// </summary>
            [EnumMember(Value = "newDevBrochurePdf")]
            NewDevBrochurePdf = 2,
            /// <summary>
            /// Enum FloorplanPdf for value: floorplanPdf
            /// </summary>
            [EnumMember(Value = "floorplanPdf")]
            FloorplanPdf = 3,
            /// <summary>
            /// Enum DevProjectPdf for value: devProjectPdf
            /// </summary>
            [EnumMember(Value = "devProjectPdf")]
            DevProjectPdf = 4        }
        /// <summary>
        /// Type of the PDF
        /// </summary>
        /// <value>Type of the PDF</value>
        [DataMember(Name="type", EmitDefaultValue=false)]
        public TypeEnum? Type { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="ListingAdminV2PropertyPdf" /> class.
        /// </summary>
        /// <param name="url">Url of the PDF (required).</param>
        /// <param name="type">Type of the PDF.</param>
        /// <param name="description">Description of the PDF.</param>
        public ListingAdminV2PropertyPdf(string url = default(string), TypeEnum? type = default(TypeEnum?), string description = default(string))
        {
            // to ensure "url" is required (not null)
            if (url == null)
            {
                throw new InvalidDataException("url is a required property for ListingAdminV2PropertyPdf and cannot be null");
            }
            else
            {
                this.Url = url;
            }
            this.Type = type;
            this.Description = description;
        }
        
        /// <summary>
        /// Url of the PDF
        /// </summary>
        /// <value>Url of the PDF</value>
        [DataMember(Name="url", EmitDefaultValue=false)]
        public string Url { get; set; }


        /// <summary>
        /// Description of the PDF
        /// </summary>
        /// <value>Description of the PDF</value>
        [DataMember(Name="description", EmitDefaultValue=false)]
        public string Description { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ListingAdminV2PropertyPdf {\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ListingAdminV2PropertyPdf);
        }

        /// <summary>
        /// Returns true if ListingAdminV2PropertyPdf instances are equal
        /// </summary>
        /// <param name="input">Instance of ListingAdminV2PropertyPdf to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ListingAdminV2PropertyPdf input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Url == input.Url ||
                    (this.Url != null &&
                    this.Url.Equals(input.Url))
                ) && 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.Description == input.Description ||
                    (this.Description != null &&
                    this.Description.Equals(input.Description))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Url != null)
                    hashCode = hashCode * 59 + this.Url.GetHashCode();
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.Description != null)
                    hashCode = hashCode * 59 + this.Description.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
