/* 
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: v2
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Domain.Client.SwaggerDateConverter;

namespace Domain.Model
{
    /// <summary>
    /// Defines PreMarket.v1.ListingStatus
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum PreMarketV1ListingStatus
    {
        /// <summary>
        /// Enum PreMarket for value: preMarket
        /// </summary>
        [EnumMember(Value = "preMarket")]
        PreMarket = 1,
        /// <summary>
        /// Enum Sold for value: sold
        /// </summary>
        [EnumMember(Value = "sold")]
        Sold = 2,
        /// <summary>
        /// Enum Listed for value: listed
        /// </summary>
        [EnumMember(Value = "listed")]
        Listed = 3,
        /// <summary>
        /// Enum Withdrawn for value: withdrawn
        /// </summary>
        [EnumMember(Value = "withdrawn")]
        Withdrawn = 4    }
}
