/* 
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: v2
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Domain.Client.SwaggerDateConverter;

namespace Domain.Model
{
    /// <summary>
    /// SchoolProfile
    /// </summary>
    [DataContract]
        public partial class SchoolProfile :  IEquatable<SchoolProfile>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SchoolProfile" /> class.
        /// </summary>
        public SchoolProfile()
        {
        }
        
        /// <summary>
        /// Website for the school
        /// </summary>
        /// <value>Website for the school</value>
        [DataMember(Name="url", EmitDefaultValue=false)]
        public string Url { get; private set; }

        /// <summary>
        /// The range of year levels offered by the school.
        /// </summary>
        /// <value>The range of year levels offered by the school.</value>
        [DataMember(Name="yearRange", EmitDefaultValue=false)]
        public string YearRange { get; private set; }

        /// <summary>
        /// The Index of Community Socio-Educational Advantage score for the school. This score is derived from a number of variables including parental school and non-school education and occupation, the school’s geographical location and proportion of Indigenous students.
        /// </summary>
        /// <value>The Index of Community Socio-Educational Advantage score for the school. This score is derived from a number of variables including parental school and non-school education and occupation, the school’s geographical location and proportion of Indigenous students.</value>
        [DataMember(Name="icsea", EmitDefaultValue=false)]
        public int? Icsea { get; private set; }

        /// <summary>
        /// The percentage of students positioned in the lowest socio-educational advantage quarter.
        /// </summary>
        /// <value>The percentage of students positioned in the lowest socio-educational advantage quarter.</value>
        [DataMember(Name="bottomSeaQuarter", EmitDefaultValue=false)]
        public int? BottomSeaQuarter { get; private set; }

        /// <summary>
        /// The percentage of students positioned in the lower middle socio-educational advantage quarter.
        /// </summary>
        /// <value>The percentage of students positioned in the lower middle socio-educational advantage quarter.</value>
        [DataMember(Name="lowerMiddleSeaQuarter", EmitDefaultValue=false)]
        public int? LowerMiddleSeaQuarter { get; private set; }

        /// <summary>
        /// The percentage of students positioned in the higher middle socio-educational advantage quarter.
        /// </summary>
        /// <value>The percentage of students positioned in the higher middle socio-educational advantage quarter.</value>
        [DataMember(Name="upperMiddleSeaQuarter", EmitDefaultValue=false)]
        public int? UpperMiddleSeaQuarter { get; private set; }

        /// <summary>
        /// The percentage of students positioned in the highest socio-educational advantage quarter.
        /// </summary>
        /// <value>The percentage of students positioned in the highest socio-educational advantage quarter.</value>
        [DataMember(Name="topSeaQuarter", EmitDefaultValue=false)]
        public int? TopSeaQuarter { get; private set; }

        /// <summary>
        /// The total number of students, including both full-time and part-time students, who are enrolled at the school in the calendar year specified.
        /// </summary>
        /// <value>The total number of students, including both full-time and part-time students, who are enrolled at the school in the calendar year specified.</value>
        [DataMember(Name="totalEnrolments", EmitDefaultValue=false)]
        public int? TotalEnrolments { get; private set; }

        /// <summary>
        /// The total number of female students, including both full-time and part-time students, who are enrolled at the school in the calendar year specified.
        /// </summary>
        /// <value>The total number of female students, including both full-time and part-time students, who are enrolled at the school in the calendar year specified.</value>
        [DataMember(Name="girlsEnrolments", EmitDefaultValue=false)]
        public int? GirlsEnrolments { get; private set; }

        /// <summary>
        /// The total number of male students, including full-time and part-time students, who are enrolled at the school in the calendar year specified.
        /// </summary>
        /// <value>The total number of male students, including full-time and part-time students, who are enrolled at the school in the calendar year specified.</value>
        [DataMember(Name="boysEnrolments", EmitDefaultValue=false)]
        public int? BoysEnrolments { get; private set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SchoolProfile {\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("  YearRange: ").Append(YearRange).Append("\n");
            sb.Append("  Icsea: ").Append(Icsea).Append("\n");
            sb.Append("  BottomSeaQuarter: ").Append(BottomSeaQuarter).Append("\n");
            sb.Append("  LowerMiddleSeaQuarter: ").Append(LowerMiddleSeaQuarter).Append("\n");
            sb.Append("  UpperMiddleSeaQuarter: ").Append(UpperMiddleSeaQuarter).Append("\n");
            sb.Append("  TopSeaQuarter: ").Append(TopSeaQuarter).Append("\n");
            sb.Append("  TotalEnrolments: ").Append(TotalEnrolments).Append("\n");
            sb.Append("  GirlsEnrolments: ").Append(GirlsEnrolments).Append("\n");
            sb.Append("  BoysEnrolments: ").Append(BoysEnrolments).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SchoolProfile);
        }

        /// <summary>
        /// Returns true if SchoolProfile instances are equal
        /// </summary>
        /// <param name="input">Instance of SchoolProfile to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SchoolProfile input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Url == input.Url ||
                    (this.Url != null &&
                    this.Url.Equals(input.Url))
                ) && 
                (
                    this.YearRange == input.YearRange ||
                    (this.YearRange != null &&
                    this.YearRange.Equals(input.YearRange))
                ) && 
                (
                    this.Icsea == input.Icsea ||
                    (this.Icsea != null &&
                    this.Icsea.Equals(input.Icsea))
                ) && 
                (
                    this.BottomSeaQuarter == input.BottomSeaQuarter ||
                    (this.BottomSeaQuarter != null &&
                    this.BottomSeaQuarter.Equals(input.BottomSeaQuarter))
                ) && 
                (
                    this.LowerMiddleSeaQuarter == input.LowerMiddleSeaQuarter ||
                    (this.LowerMiddleSeaQuarter != null &&
                    this.LowerMiddleSeaQuarter.Equals(input.LowerMiddleSeaQuarter))
                ) && 
                (
                    this.UpperMiddleSeaQuarter == input.UpperMiddleSeaQuarter ||
                    (this.UpperMiddleSeaQuarter != null &&
                    this.UpperMiddleSeaQuarter.Equals(input.UpperMiddleSeaQuarter))
                ) && 
                (
                    this.TopSeaQuarter == input.TopSeaQuarter ||
                    (this.TopSeaQuarter != null &&
                    this.TopSeaQuarter.Equals(input.TopSeaQuarter))
                ) && 
                (
                    this.TotalEnrolments == input.TotalEnrolments ||
                    (this.TotalEnrolments != null &&
                    this.TotalEnrolments.Equals(input.TotalEnrolments))
                ) && 
                (
                    this.GirlsEnrolments == input.GirlsEnrolments ||
                    (this.GirlsEnrolments != null &&
                    this.GirlsEnrolments.Equals(input.GirlsEnrolments))
                ) && 
                (
                    this.BoysEnrolments == input.BoysEnrolments ||
                    (this.BoysEnrolments != null &&
                    this.BoysEnrolments.Equals(input.BoysEnrolments))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Url != null)
                    hashCode = hashCode * 59 + this.Url.GetHashCode();
                if (this.YearRange != null)
                    hashCode = hashCode * 59 + this.YearRange.GetHashCode();
                if (this.Icsea != null)
                    hashCode = hashCode * 59 + this.Icsea.GetHashCode();
                if (this.BottomSeaQuarter != null)
                    hashCode = hashCode * 59 + this.BottomSeaQuarter.GetHashCode();
                if (this.LowerMiddleSeaQuarter != null)
                    hashCode = hashCode * 59 + this.LowerMiddleSeaQuarter.GetHashCode();
                if (this.UpperMiddleSeaQuarter != null)
                    hashCode = hashCode * 59 + this.UpperMiddleSeaQuarter.GetHashCode();
                if (this.TopSeaQuarter != null)
                    hashCode = hashCode * 59 + this.TopSeaQuarter.GetHashCode();
                if (this.TotalEnrolments != null)
                    hashCode = hashCode * 59 + this.TotalEnrolments.GetHashCode();
                if (this.GirlsEnrolments != null)
                    hashCode = hashCode * 59 + this.GirlsEnrolments.GetHashCode();
                if (this.BoysEnrolments != null)
                    hashCode = hashCode * 59 + this.BoysEnrolments.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
