/* 
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: v2
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = Domain.Client.SwaggerDateConverter;

namespace Domain.Model
{
    /// <summary>
    /// Defines SuburbPerformancePeriodSize
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
        public enum SuburbPerformancePeriodSize
    {
        /// <summary>
        /// Enum Quarters for value: Quarters
        /// </summary>
        [EnumMember(Value = "Quarters")]
        Quarters = 1,
        /// <summary>
        /// Enum HalfYears for value: HalfYears
        /// </summary>
        [EnumMember(Value = "HalfYears")]
        HalfYears = 2,
        /// <summary>
        /// Enum Years for value: Years
        /// </summary>
        [EnumMember(Value = "Years")]
        Years = 3    }
}
