/* 
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: v2
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api;
using Domain.Model;
using Domain.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Test
{
    /// <summary>
    ///  Class for testing ListingAdminV2OffMarketDetailsBase
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ListingAdminV2OffMarketDetailsBaseTests
    {
        // TODO uncomment below to declare an instance variable for ListingAdminV2OffMarketDetailsBase
        //private ListingAdminV2OffMarketDetailsBase instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ListingAdminV2OffMarketDetailsBase
            //instance = new ListingAdminV2OffMarketDetailsBase();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ListingAdminV2OffMarketDetailsBase
        /// </summary>
        [Test]
        public void ListingAdminV2OffMarketDetailsBaseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ListingAdminV2OffMarketDetailsBase
            //Assert.IsInstanceOfType<ListingAdminV2OffMarketDetailsBase> (instance, "variable 'instance' is a ListingAdminV2OffMarketDetailsBase");
        }


        /// <summary>
        /// Test the property 'OffMarketAction'
        /// </summary>
        [Test]
        public void OffMarketActionTest()
        {
            // TODO unit test for the property 'OffMarketAction'
        }
        /// <summary>
        /// Test the property 'ActionDate'
        /// </summary>
        [Test]
        public void ActionDateTest()
        {
            // TODO unit test for the property 'ActionDate'
        }
        /// <summary>
        /// Test the property 'SoldDetails'
        /// </summary>
        [Test]
        public void SoldDetailsTest()
        {
            // TODO unit test for the property 'SoldDetails'
        }
        /// <summary>
        /// Test the property 'LeasedDetails'
        /// </summary>
        [Test]
        public void LeasedDetailsTest()
        {
            // TODO unit test for the property 'LeasedDetails'
        }
        /// <summary>
        /// Test the property 'Comment'
        /// </summary>
        [Test]
        public void CommentTest()
        {
            // TODO unit test for the property 'Comment'
        }

    }

}
