/* 
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: v2
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api;
using Domain.Model;
using Domain.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Test
{
    /// <summary>
    ///  Class for testing ListingAdminV2ResidentialOffMarketListing
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ListingAdminV2ResidentialOffMarketListingTests
    {
        // TODO uncomment below to declare an instance variable for ListingAdminV2ResidentialOffMarketListing
        //private ListingAdminV2ResidentialOffMarketListing instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ListingAdminV2ResidentialOffMarketListing
            //instance = new ListingAdminV2ResidentialOffMarketListing();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ListingAdminV2ResidentialOffMarketListing
        /// </summary>
        [Test]
        public void ListingAdminV2ResidentialOffMarketListingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ListingAdminV2ResidentialOffMarketListing
            //Assert.IsInstanceOfType<ListingAdminV2ResidentialOffMarketListing> (instance, "variable 'instance' is a ListingAdminV2ResidentialOffMarketListing");
        }


        /// <summary>
        /// Test the property 'DomainAdId'
        /// </summary>
        [Test]
        public void DomainAdIdTest()
        {
            // TODO unit test for the property 'DomainAdId'
        }
        /// <summary>
        /// Test the property 'InspectionDetails'
        /// </summary>
        [Test]
        public void InspectionDetailsTest()
        {
            // TODO unit test for the property 'InspectionDetails'
        }
        /// <summary>
        /// Test the property 'IsRural'
        /// </summary>
        [Test]
        public void IsRuralTest()
        {
            // TODO unit test for the property 'IsRural'
        }
        /// <summary>
        /// Test the property 'ListingProvider'
        /// </summary>
        [Test]
        public void ListingProviderTest()
        {
            // TODO unit test for the property 'ListingProvider'
        }
        /// <summary>
        /// Test the property 'DomainAgencyID'
        /// </summary>
        [Test]
        public void DomainAgencyIDTest()
        {
            // TODO unit test for the property 'DomainAgencyID'
        }
        /// <summary>
        /// Test the property 'ProviderAdId'
        /// </summary>
        [Test]
        public void ProviderAdIdTest()
        {
            // TODO unit test for the property 'ProviderAdId'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'Summary'
        /// </summary>
        [Test]
        public void SummaryTest()
        {
            // TODO unit test for the property 'Summary'
        }
        /// <summary>
        /// Test the property 'Contacts'
        /// </summary>
        [Test]
        public void ContactsTest()
        {
            // TODO unit test for the property 'Contacts'
        }
        /// <summary>
        /// Test the property 'ListingAction'
        /// </summary>
        [Test]
        public void ListingActionTest()
        {
            // TODO unit test for the property 'ListingAction'
        }
        /// <summary>
        /// Test the property 'OffMarketDetails'
        /// </summary>
        [Test]
        public void OffMarketDetailsTest()
        {
            // TODO unit test for the property 'OffMarketDetails'
        }
        /// <summary>
        /// Test the property 'PropertyDetails'
        /// </summary>
        [Test]
        public void PropertyDetailsTest()
        {
            // TODO unit test for the property 'PropertyDetails'
        }

    }

}
