/* 
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: v2
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api;
using Domain.Model;
using Domain.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Test
{
    /// <summary>
    ///  Class for testing ListingAdminV2Inspection
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ListingAdminV2InspectionTests
    {
        // TODO uncomment below to declare an instance variable for ListingAdminV2Inspection
        //private ListingAdminV2Inspection instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ListingAdminV2Inspection
            //instance = new ListingAdminV2Inspection();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ListingAdminV2Inspection
        /// </summary>
        [Test]
        public void ListingAdminV2InspectionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ListingAdminV2Inspection
            //Assert.IsInstanceOfType<ListingAdminV2Inspection> (instance, "variable 'instance' is a ListingAdminV2Inspection");
        }


        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Test]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Test]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }
        /// <summary>
        /// Test the property 'Repeat'
        /// </summary>
        [Test]
        public void RepeatTest()
        {
            // TODO unit test for the property 'Repeat'
        }

    }

}
