/* 
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: v2
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api;
using Domain.Model;
using Domain.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Test
{
    /// <summary>
    ///  Class for testing ListingAdminV2Parking
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ListingAdminV2ParkingTests
    {
        // TODO uncomment below to declare an instance variable for ListingAdminV2Parking
        //private ListingAdminV2Parking instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ListingAdminV2Parking
            //instance = new ListingAdminV2Parking();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ListingAdminV2Parking
        /// </summary>
        [Test]
        public void ListingAdminV2ParkingInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ListingAdminV2Parking
            //Assert.IsInstanceOfType<ListingAdminV2Parking> (instance, "variable 'instance' is a ListingAdminV2Parking");
        }


        /// <summary>
        /// Test the property 'ParkingType'
        /// </summary>
        [Test]
        public void ParkingTypeTest()
        {
            // TODO unit test for the property 'ParkingType'
        }
        /// <summary>
        /// Test the property 'NumberOnSite'
        /// </summary>
        [Test]
        public void NumberOnSiteTest()
        {
            // TODO unit test for the property 'NumberOnSite'
        }
        /// <summary>
        /// Test the property 'Information'
        /// </summary>
        [Test]
        public void InformationTest()
        {
            // TODO unit test for the property 'Information'
        }

    }

}
