/* 
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: v2
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api;
using Domain.Model;
using Domain.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Test
{
    /// <summary>
    ///  Class for testing ListingAdminV2EOI
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ListingAdminV2EOITests
    {
        // TODO uncomment below to declare an instance variable for ListingAdminV2EOI
        //private ListingAdminV2EOI instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ListingAdminV2EOI
            //instance = new ListingAdminV2EOI();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ListingAdminV2EOI
        /// </summary>
        [Test]
        public void ListingAdminV2EOIInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ListingAdminV2EOI
            //Assert.IsInstanceOfType<ListingAdminV2EOI> (instance, "variable 'instance' is a ListingAdminV2EOI");
        }


        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'EndDate'
        /// </summary>
        [Test]
        public void EndDateTest()
        {
            // TODO unit test for the property 'EndDate'
        }
        /// <summary>
        /// Test the property 'RecipientName'
        /// </summary>
        [Test]
        public void RecipientNameTest()
        {
            // TODO unit test for the property 'RecipientName'
        }

    }

}
