/* 
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: v2
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api;
using Domain.Model;
using Domain.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Test
{
    /// <summary>
    ///  Class for testing ListingAdminV2Address
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ListingAdminV2AddressTests
    {
        // TODO uncomment below to declare an instance variable for ListingAdminV2Address
        //private ListingAdminV2Address instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ListingAdminV2Address
            //instance = new ListingAdminV2Address();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ListingAdminV2Address
        /// </summary>
        [Test]
        public void ListingAdminV2AddressInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ListingAdminV2Address
            //Assert.IsInstanceOfType<ListingAdminV2Address> (instance, "variable 'instance' is a ListingAdminV2Address");
        }


        /// <summary>
        /// Test the property 'UnitNumber'
        /// </summary>
        [Test]
        public void UnitNumberTest()
        {
            // TODO unit test for the property 'UnitNumber'
        }
        /// <summary>
        /// Test the property 'Street'
        /// </summary>
        [Test]
        public void StreetTest()
        {
            // TODO unit test for the property 'Street'
        }
        /// <summary>
        /// Test the property 'DisplayOption'
        /// </summary>
        [Test]
        public void DisplayOptionTest()
        {
            // TODO unit test for the property 'DisplayOption'
        }
        /// <summary>
        /// Test the property 'SuggestedGeoLocation'
        /// </summary>
        [Test]
        public void SuggestedGeoLocationTest()
        {
            // TODO unit test for the property 'SuggestedGeoLocation'
        }
        /// <summary>
        /// Test the property 'StreetNumber'
        /// </summary>
        [Test]
        public void StreetNumberTest()
        {
            // TODO unit test for the property 'StreetNumber'
        }
        /// <summary>
        /// Test the property 'Suburb'
        /// </summary>
        [Test]
        public void SuburbTest()
        {
            // TODO unit test for the property 'Suburb'
        }
        /// <summary>
        /// Test the property 'Postcode'
        /// </summary>
        [Test]
        public void PostcodeTest()
        {
            // TODO unit test for the property 'Postcode'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

    }

}
