/* 
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: v2
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api;
using Domain.Model;
using Domain.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Test
{
    /// <summary>
    ///  Class for testing ListingAdminV2Contact
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ListingAdminV2ContactTests
    {
        // TODO uncomment below to declare an instance variable for ListingAdminV2Contact
        //private ListingAdminV2Contact instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ListingAdminV2Contact
            //instance = new ListingAdminV2Contact();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ListingAdminV2Contact
        /// </summary>
        [Test]
        public void ListingAdminV2ContactInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ListingAdminV2Contact
            //Assert.IsInstanceOfType<ListingAdminV2Contact> (instance, "variable 'instance' is a ListingAdminV2Contact");
        }


        /// <summary>
        /// Test the property 'DomainAgentId'
        /// </summary>
        [Test]
        public void DomainAgentIdTest()
        {
            // TODO unit test for the property 'DomainAgentId'
        }
        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Test]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }
        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Test]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }
        /// <summary>
        /// Test the property 'Phone'
        /// </summary>
        [Test]
        public void PhoneTest()
        {
            // TODO unit test for the property 'Phone'
        }
        /// <summary>
        /// Test the property 'Fax'
        /// </summary>
        [Test]
        public void FaxTest()
        {
            // TODO unit test for the property 'Fax'
        }
        /// <summary>
        /// Test the property 'Mobile'
        /// </summary>
        [Test]
        public void MobileTest()
        {
            // TODO unit test for the property 'Mobile'
        }
        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Test]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }
        /// <summary>
        /// Test the property 'ReceiveEmails'
        /// </summary>
        [Test]
        public void ReceiveEmailsTest()
        {
            // TODO unit test for the property 'ReceiveEmails'
        }

    }

}
