/* 
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: v2
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api;
using Domain.Model;
using Domain.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Test
{
    /// <summary>
    ///  Class for testing ListingAdminV2CommercialPrice
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ListingAdminV2CommercialPriceTests
    {
        // TODO uncomment below to declare an instance variable for ListingAdminV2CommercialPrice
        //private ListingAdminV2CommercialPrice instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ListingAdminV2CommercialPrice
            //instance = new ListingAdminV2CommercialPrice();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ListingAdminV2CommercialPrice
        /// </summary>
        [Test]
        public void ListingAdminV2CommercialPriceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ListingAdminV2CommercialPrice
            //Assert.IsInstanceOfType<ListingAdminV2CommercialPrice> (instance, "variable 'instance' is a ListingAdminV2CommercialPrice");
        }


        /// <summary>
        /// Test the property 'PriceUnitType'
        /// </summary>
        [Test]
        public void PriceUnitTypeTest()
        {
            // TODO unit test for the property 'PriceUnitType'
        }
        /// <summary>
        /// Test the property 'PriceType'
        /// </summary>
        [Test]
        public void PriceTypeTest()
        {
            // TODO unit test for the property 'PriceType'
        }
        /// <summary>
        /// Test the property 'GstOptionType'
        /// </summary>
        [Test]
        public void GstOptionTypeTest()
        {
            // TODO unit test for the property 'GstOptionType'
        }
        /// <summary>
        /// Test the property 'PriceReduction'
        /// </summary>
        [Test]
        public void PriceReductionTest()
        {
            // TODO unit test for the property 'PriceReduction'
        }
        /// <summary>
        /// Test the property 'DisplayText'
        /// </summary>
        [Test]
        public void DisplayTextTest()
        {
            // TODO unit test for the property 'DisplayText'
        }
        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Test]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }
        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Test]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }

    }

}
