/* 
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: v2
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api;
using Domain.Model;
using Domain.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Test
{
    /// <summary>
    ///  Class for testing ListingAdminV2SpecificUnitDetail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ListingAdminV2SpecificUnitDetailTests
    {
        // TODO uncomment below to declare an instance variable for ListingAdminV2SpecificUnitDetail
        //private ListingAdminV2SpecificUnitDetail instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ListingAdminV2SpecificUnitDetail
            //instance = new ListingAdminV2SpecificUnitDetail();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ListingAdminV2SpecificUnitDetail
        /// </summary>
        [Test]
        public void ListingAdminV2SpecificUnitDetailInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ListingAdminV2SpecificUnitDetail
            //Assert.IsInstanceOfType<ListingAdminV2SpecificUnitDetail> (instance, "variable 'instance' is a ListingAdminV2SpecificUnitDetail");
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Test]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Test]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Test]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'Notes'
        /// </summary>
        [Test]
        public void NotesTest()
        {
            // TODO unit test for the property 'Notes'
        }
        /// <summary>
        /// Test the property 'IsSoldOrLeased'
        /// </summary>
        [Test]
        public void IsSoldOrLeasedTest()
        {
            // TODO unit test for the property 'IsSoldOrLeased'
        }
        /// <summary>
        /// Test the property 'Occupancy'
        /// </summary>
        [Test]
        public void OccupancyTest()
        {
            // TODO unit test for the property 'Occupancy'
        }
        /// <summary>
        /// Test the property 'PriceUnit'
        /// </summary>
        [Test]
        public void PriceUnitTest()
        {
            // TODO unit test for the property 'PriceUnit'
        }
        /// <summary>
        /// Test the property 'LeasePriceForSaleorLease'
        /// </summary>
        [Test]
        public void LeasePriceForSaleorLeaseTest()
        {
            // TODO unit test for the property 'LeasePriceForSaleorLease'
        }

    }

}
