/* 
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: v2
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api;
using Domain.Model;
using Domain.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Test
{
    /// <summary>
    ///  Class for testing ListingAdminV2Lease
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ListingAdminV2LeaseTests
    {
        // TODO uncomment below to declare an instance variable for ListingAdminV2Lease
        //private ListingAdminV2Lease instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ListingAdminV2Lease
            //instance = new ListingAdminV2Lease();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ListingAdminV2Lease
        /// </summary>
        [Test]
        public void ListingAdminV2LeaseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ListingAdminV2Lease
            //Assert.IsInstanceOfType<ListingAdminV2Lease> (instance, "variable 'instance' is a ListingAdminV2Lease");
        }


        /// <summary>
        /// Test the property 'TermOfLeaseFrom'
        /// </summary>
        [Test]
        public void TermOfLeaseFromTest()
        {
            // TODO unit test for the property 'TermOfLeaseFrom'
        }
        /// <summary>
        /// Test the property 'TermOfLeaseTo'
        /// </summary>
        [Test]
        public void TermOfLeaseToTest()
        {
            // TODO unit test for the property 'TermOfLeaseTo'
        }
        /// <summary>
        /// Test the property 'LeaseOutgoings'
        /// </summary>
        [Test]
        public void LeaseOutgoingsTest()
        {
            // TODO unit test for the property 'LeaseOutgoings'
        }

    }

}
