/* 
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: v2
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api;
using Domain.Model;
using Domain.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Test
{
    /// <summary>
    ///  Class for testing ListingAdminV2ListingResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class ListingAdminV2ListingResponseTests
    {
        // TODO uncomment below to declare an instance variable for ListingAdminV2ListingResponse
        //private ListingAdminV2ListingResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of ListingAdminV2ListingResponse
            //instance = new ListingAdminV2ListingResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ListingAdminV2ListingResponse
        /// </summary>
        [Test]
        public void ListingAdminV2ListingResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" ListingAdminV2ListingResponse
            //Assert.IsInstanceOfType<ListingAdminV2ListingResponse> (instance, "variable 'instance' is a ListingAdminV2ListingResponse");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'AgencyId'
        /// </summary>
        [Test]
        public void AgencyIdTest()
        {
            // TODO unit test for the property 'AgencyId'
        }
        /// <summary>
        /// Test the property 'ProviderId'
        /// </summary>
        [Test]
        public void ProviderIdTest()
        {
            // TODO unit test for the property 'ProviderId'
        }
        /// <summary>
        /// Test the property 'ProviderAdId'
        /// </summary>
        [Test]
        public void ProviderAdIdTest()
        {
            // TODO unit test for the property 'ProviderAdId'
        }
        /// <summary>
        /// Test the property 'VersionId'
        /// </summary>
        [Test]
        public void VersionIdTest()
        {
            // TODO unit test for the property 'VersionId'
        }
        /// <summary>
        /// Test the property 'ProcessStatus'
        /// </summary>
        [Test]
        public void ProcessStatusTest()
        {
            // TODO unit test for the property 'ProcessStatus'
        }

    }

}
