/* 
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: v2
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api;
using Domain.Model;
using Domain.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Test
{
    /// <summary>
    ///  Class for testing PreMarketV1ListingRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PreMarketV1ListingRequestTests
    {
        // TODO uncomment below to declare an instance variable for PreMarketV1ListingRequest
        //private PreMarketV1ListingRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PreMarketV1ListingRequest
            //instance = new PreMarketV1ListingRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PreMarketV1ListingRequest
        /// </summary>
        [Test]
        public void PreMarketV1ListingRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PreMarketV1ListingRequest
            //Assert.IsInstanceOfType<PreMarketV1ListingRequest> (instance, "variable 'instance' is a PreMarketV1ListingRequest");
        }


        /// <summary>
        /// Test the property 'ListingStatus'
        /// </summary>
        [Test]
        public void ListingStatusTest()
        {
            // TODO unit test for the property 'ListingStatus'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'DomainAgencyId'
        /// </summary>
        [Test]
        public void DomainAgencyIdTest()
        {
            // TODO unit test for the property 'DomainAgencyId'
        }
        /// <summary>
        /// Test the property 'ListingProvider'
        /// </summary>
        [Test]
        public void ListingProviderTest()
        {
            // TODO unit test for the property 'ListingProvider'
        }
        /// <summary>
        /// Test the property 'ProviderAdId'
        /// </summary>
        [Test]
        public void ProviderAdIdTest()
        {
            // TODO unit test for the property 'ProviderAdId'
        }
        /// <summary>
        /// Test the property 'Contacts'
        /// </summary>
        [Test]
        public void ContactsTest()
        {
            // TODO unit test for the property 'Contacts'
        }
        /// <summary>
        /// Test the property 'Bedrooms'
        /// </summary>
        [Test]
        public void BedroomsTest()
        {
            // TODO unit test for the property 'Bedrooms'
        }
        /// <summary>
        /// Test the property 'Bathrooms'
        /// </summary>
        [Test]
        public void BathroomsTest()
        {
            // TODO unit test for the property 'Bathrooms'
        }
        /// <summary>
        /// Test the property 'Carspaces'
        /// </summary>
        [Test]
        public void CarspacesTest()
        {
            // TODO unit test for the property 'Carspaces'
        }
        /// <summary>
        /// Test the property 'Summary'
        /// </summary>
        [Test]
        public void SummaryTest()
        {
            // TODO unit test for the property 'Summary'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'AuthorityExecutedDate'
        /// </summary>
        [Test]
        public void AuthorityExecutedDateTest()
        {
            // TODO unit test for the property 'AuthorityExecutedDate'
        }
        /// <summary>
        /// Test the property 'ReservePrice'
        /// </summary>
        [Test]
        public void ReservePriceTest()
        {
            // TODO unit test for the property 'ReservePrice'
        }
        /// <summary>
        /// Test the property 'EstimatedSalePrice'
        /// </summary>
        [Test]
        public void EstimatedSalePriceTest()
        {
            // TODO unit test for the property 'EstimatedSalePrice'
        }
        /// <summary>
        /// Test the property 'PropertyTypes'
        /// </summary>
        [Test]
        public void PropertyTypesTest()
        {
            // TODO unit test for the property 'PropertyTypes'
        }
        /// <summary>
        /// Test the property 'AuthorityType'
        /// </summary>
        [Test]
        public void AuthorityTypeTest()
        {
            // TODO unit test for the property 'AuthorityType'
        }
        /// <summary>
        /// Test the property 'ExclusivePeriodDays'
        /// </summary>
        [Test]
        public void ExclusivePeriodDaysTest()
        {
            // TODO unit test for the property 'ExclusivePeriodDays'
        }
        /// <summary>
        /// Test the property 'ExclusiveContinuingPeriodDays'
        /// </summary>
        [Test]
        public void ExclusiveContinuingPeriodDaysTest()
        {
            // TODO unit test for the property 'ExclusiveContinuingPeriodDays'
        }
        /// <summary>
        /// Test the property 'ExclusivePeriodStartDate'
        /// </summary>
        [Test]
        public void ExclusivePeriodStartDateTest()
        {
            // TODO unit test for the property 'ExclusivePeriodStartDate'
        }
        /// <summary>
        /// Test the property 'ActionDate'
        /// </summary>
        [Test]
        public void ActionDateTest()
        {
            // TODO unit test for the property 'ActionDate'
        }
        /// <summary>
        /// Test the property 'StatementOfInformation'
        /// </summary>
        [Test]
        public void StatementOfInformationTest()
        {
            // TODO unit test for the property 'StatementOfInformation'
        }
        /// <summary>
        /// Test the property 'Images'
        /// </summary>
        [Test]
        public void ImagesTest()
        {
            // TODO unit test for the property 'Images'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

    }

}
