/* 
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: v2
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api;
using Domain.Model;
using Domain.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Test
{
    /// <summary>
    ///  Class for testing PreMarketV1ProblemDetails
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PreMarketV1ProblemDetailsTests
    {
        // TODO uncomment below to declare an instance variable for PreMarketV1ProblemDetails
        //private PreMarketV1ProblemDetails instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PreMarketV1ProblemDetails
            //instance = new PreMarketV1ProblemDetails();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PreMarketV1ProblemDetails
        /// </summary>
        [Test]
        public void PreMarketV1ProblemDetailsInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PreMarketV1ProblemDetails
            //Assert.IsInstanceOfType<PreMarketV1ProblemDetails> (instance, "variable 'instance' is a PreMarketV1ProblemDetails");
        }



    }

}
