/* 
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: v2
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api;
using Domain.Model;
using Domain.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Test
{
    /// <summary>
    ///  Class for testing PreMarketV1ListingResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PreMarketV1ListingResponseTests
    {
        // TODO uncomment below to declare an instance variable for PreMarketV1ListingResponse
        //private PreMarketV1ListingResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PreMarketV1ListingResponse
            //instance = new PreMarketV1ListingResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PreMarketV1ListingResponse
        /// </summary>
        [Test]
        public void PreMarketV1ListingResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PreMarketV1ListingResponse
            //Assert.IsInstanceOfType<PreMarketV1ListingResponse> (instance, "variable 'instance' is a PreMarketV1ListingResponse");
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Test]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'ListingStatus'
        /// </summary>
        [Test]
        public void ListingStatusTest()
        {
            // TODO unit test for the property 'ListingStatus'
        }
        /// <summary>
        /// Test the property 'ProviderDetails'
        /// </summary>
        [Test]
        public void ProviderDetailsTest()
        {
            // TODO unit test for the property 'ProviderDetails'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Test]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'AdvertiserIdentifiers'
        /// </summary>
        [Test]
        public void AdvertiserIdentifiersTest()
        {
            // TODO unit test for the property 'AdvertiserIdentifiers'
        }
        /// <summary>
        /// Test the property 'Bedrooms'
        /// </summary>
        [Test]
        public void BedroomsTest()
        {
            // TODO unit test for the property 'Bedrooms'
        }
        /// <summary>
        /// Test the property 'Bathrooms'
        /// </summary>
        [Test]
        public void BathroomsTest()
        {
            // TODO unit test for the property 'Bathrooms'
        }
        /// <summary>
        /// Test the property 'Carspaces'
        /// </summary>
        [Test]
        public void CarspacesTest()
        {
            // TODO unit test for the property 'Carspaces'
        }
        /// <summary>
        /// Test the property 'Headline'
        /// </summary>
        [Test]
        public void HeadlineTest()
        {
            // TODO unit test for the property 'Headline'
        }
        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Test]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }
        /// <summary>
        /// Test the property 'AuthorityExecutedDate'
        /// </summary>
        [Test]
        public void AuthorityExecutedDateTest()
        {
            // TODO unit test for the property 'AuthorityExecutedDate'
        }
        /// <summary>
        /// Test the property 'EstimatedSalePrice'
        /// </summary>
        [Test]
        public void EstimatedSalePriceTest()
        {
            // TODO unit test for the property 'EstimatedSalePrice'
        }
        /// <summary>
        /// Test the property 'PropertyTypes'
        /// </summary>
        [Test]
        public void PropertyTypesTest()
        {
            // TODO unit test for the property 'PropertyTypes'
        }
        /// <summary>
        /// Test the property 'AuthorityType'
        /// </summary>
        [Test]
        public void AuthorityTypeTest()
        {
            // TODO unit test for the property 'AuthorityType'
        }
        /// <summary>
        /// Test the property 'ExclusivePeriodDays'
        /// </summary>
        [Test]
        public void ExclusivePeriodDaysTest()
        {
            // TODO unit test for the property 'ExclusivePeriodDays'
        }
        /// <summary>
        /// Test the property 'ExclusiveContinuingPeriodDays'
        /// </summary>
        [Test]
        public void ExclusiveContinuingPeriodDaysTest()
        {
            // TODO unit test for the property 'ExclusiveContinuingPeriodDays'
        }
        /// <summary>
        /// Test the property 'ExclusivePeriodStartDate'
        /// </summary>
        [Test]
        public void ExclusivePeriodStartDateTest()
        {
            // TODO unit test for the property 'ExclusivePeriodStartDate'
        }
        /// <summary>
        /// Test the property 'GeoLocation'
        /// </summary>
        [Test]
        public void GeoLocationTest()
        {
            // TODO unit test for the property 'GeoLocation'
        }
        /// <summary>
        /// Test the property 'MapCertainty'
        /// </summary>
        [Test]
        public void MapCertaintyTest()
        {
            // TODO unit test for the property 'MapCertainty'
        }
        /// <summary>
        /// Test the property 'Media'
        /// </summary>
        [Test]
        public void MediaTest()
        {
            // TODO unit test for the property 'Media'
        }
        /// <summary>
        /// Test the property 'PropertyId'
        /// </summary>
        [Test]
        public void PropertyIdTest()
        {
            // TODO unit test for the property 'PropertyId'
        }
        /// <summary>
        /// Test the property 'StatementOfInformation'
        /// </summary>
        [Test]
        public void StatementOfInformationTest()
        {
            // TODO unit test for the property 'StatementOfInformation'
        }
        /// <summary>
        /// Test the property 'DateCreated'
        /// </summary>
        [Test]
        public void DateCreatedTest()
        {
            // TODO unit test for the property 'DateCreated'
        }
        /// <summary>
        /// Test the property 'DateUpdated'
        /// </summary>
        [Test]
        public void DateUpdatedTest()
        {
            // TODO unit test for the property 'DateUpdated'
        }
        /// <summary>
        /// Test the property 'DateWithdrawn'
        /// </summary>
        [Test]
        public void DateWithdrawnTest()
        {
            // TODO unit test for the property 'DateWithdrawn'
        }
        /// <summary>
        /// Test the property 'DateListed'
        /// </summary>
        [Test]
        public void DateListedTest()
        {
            // TODO unit test for the property 'DateListed'
        }
        /// <summary>
        /// Test the property 'DateSold'
        /// </summary>
        [Test]
        public void DateSoldTest()
        {
            // TODO unit test for the property 'DateSold'
        }
        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Test]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

    }

}
