/* 
 * Domain Public API
 *
 * See https://developer.domain.com.au for more information
 *
 * OpenAPI spec version: v2
 * Contact: api@domain.com.au
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Domain.Api;
using Domain.Model;
using Domain.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Domain.Test
{
    /// <summary>
    ///  Class for testing SuburbPerformancePeriodSize
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SuburbPerformancePeriodSizeTests
    {
        // TODO uncomment below to declare an instance variable for SuburbPerformancePeriodSize
        //private SuburbPerformancePeriodSize instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SuburbPerformancePeriodSize
            //instance = new SuburbPerformancePeriodSize();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SuburbPerformancePeriodSize
        /// </summary>
        [Test]
        public void SuburbPerformancePeriodSizeInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SuburbPerformancePeriodSize
            //Assert.IsInstanceOfType<SuburbPerformancePeriodSize> (instance, "variable 'instance' is a SuburbPerformancePeriodSize");
        }



    }

}
